# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 00:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=30)),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('Position', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=70)),
                ('Bio_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Workout_Name', models.CharField(max_length=100)),
                ('Workout_Description', models.TextField()),
                ('Position', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Workout_Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Shots_Made', models.IntegerField()),
                ('Shots_Attempted', models.IntegerField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.User')),
                ('Workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.Workout')),
            ],
        ),
    ]
