# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import workouts.models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_workout_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Profile_Pic',
            field=models.ImageField(default='default_user.png', upload_to=workouts.models.get_image_path),
        ),
    ]
