# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Profile_Pic',
            field=models.ImageField(blank=True, upload_to='Profile_Image'),
        ),
    ]
