# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_auto_20170725_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Profile_Pic',
            field=models.FileField(default='/Profile_Image/default_user.png', upload_to=''),
        ),
    ]
