# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_auto_20170731_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Profile_Pic',
            field=models.FileField(upload_to=''),
        ),
    ]
